# 名字随意
name: deploy to my tencent
# 触发机制, 可以定时, 或其他, 具体可自行百度, 示例为main分支push时触发
on:
  push:
    branches:
      - master
# 要执行的计划
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@master
      - name: use Node 18
        uses: actions/setup-node@v1
        with: 
          node-version: 18
      - name: npm install
        run: |
          npm install
        env:
         CI: true
      - name: vitepress build
        run: |
          npm run docs:build
        env:
          CI: true
      - name: show builded files
        run: |
          cd .vitepress/dist
          ls -alh
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: "-avz --delete"
          SOURCE: ".vuepress/dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
